# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    com.ibatis: INFO

spring:
  application:
    name: rest-service
  datasource:
    url: jdbc:mysql://localhost:3306/community?autoReconnect=true&autoReconnectForPools=true&useSSL=false&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&socketTimeout=600000
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

security:
  oauth2:
    resource:
      filter-order: 3

mybatis:
  typeAliasesPackage: org.community.domain
  mapperLocations: classpath*:mybatis/sqlmap/**/*.xml


server:
#  context-path: /rest
  port: 8080


